GAME_TITLE = "Chess"

SPRITE_SIZE = 32
SPRITE_SCALE = 2
IMAGE_SIZE = SPRITE_SIZE * SPRITE_SCALE
# Adjust dimension to fit the chess board
SCREEN_WIDTH = 16 * IMAGE_SIZE
SCREEN_HEIGHT = 16 * IMAGE_SIZE

BLACK = (0, 0, 0)

BLACK_SQUARE = (0, 0, 0)
WHITE_SQUARE = (255, 255, 255)